### ISSUE TITLE
Change opacity or darken unfocused panes?

### ISSUE THREAD

**Issue by ef2k** [geksilla/atom-golden-ratio#1]
Hi, thanks for a great plugin! Is it possible to change the opacity of the unfocused panes?

**Comment by redfellow** [comment]
You could add this to your custom stylesheet. I don't think this belongs to the golden ratio package, at least as a default.

```
atom-text-editor:not(.is-focused) {
	opacity: 0.4;
	transition: opacity 175ms linear;
}

atom-text-editor.is-focused {
	transition: opacity 175ms linear;
        opacity: 1;
}
```

**Comment by ef2k** [comment]
That's helpful, thank you.
